---
title: Introduction to Shell Scripts
---

So far, we have seen many commands provided by the system, and seen how to combine them to do interesting things. In this session, we are going to learn how to make own scripts, programs that work just like the commands provided by the system. 

## The Setup

Before we start, we need to learn how to create and edit files. Please follow the instructions in [Setting up editor](../setup/editor.qmd).

## Getting Started

Use `nano` to create a file `hello.sh` with the following contents. You'll have to type `nano hello.sh` and enter the contents.

```{.bash filename="hello.sh"}
echo "Hello, world!"
```

Let's check if we have the file.

```session
$ ls
hello.sh
```

Let's see what is in the file.

```session
$ cat hello.sh
echo "Hello, world!"
```

Now let's run the script.

```session
$ bash hello.sh
Hello, world!
```

A script could have multiple commands. When you run the script, all the commands are executed one by one. For example try the following script.

```bash {filename=welcome.sh}
figlet "Welcome $USER"

echo 
echo "---"
echo "The time is: $(date)"
echo "current directory: $(pwd)"
echo "The files in the directory:"
ls
```

And when you run it:

```session
$ bash welcome.sh

```

### Example: figdate.sh

Let's write a script to display the date using let. If you remember from the previous sessions, we could do `date | figlet` to pipe the output of date as input to figlet. We just need to put that in a shell script.


```bash {filename=figdate.sh}
date | figlet
```

## Variables

In shell, we could define variables to store some values. 

A variable is defined using the following way:

```
some_variable=some_value
```

And to the value of a varaible, we use `$some_variable`.

```session
$ name=alice
$ echo $name
alice
```


::: {.callout-caution collapse="true"}



This is an example of a 'folded' caution callout that can be expanded by the user. You can use `collapse="true"` to collapse it by default or `collapse="false"` to make a collapsible callout that is expanded by default.
:::


## Arguments


## Loops

```bash {filename=hello-all.sh}
for name in alice bob charlie dave
do 
    echo "Hello, $name!"
done
```

```session
$ bash hello-all.sh
Hello, Alice!
Hello, Bob!
Hello, Charlie!
Hello, Dave!
```

We could do the same by passing the names as arguments.

```bash {filename=hello-all.sh}
for name in $*
do 
    echo "Hello, $name!"
done
```

```session
$ bash hello-all.sh Alice
Hello, Alice!
```

```session
$ bash hello-all.sh Alice Bob
Hello, Alice!
Hello, Bob!
```

```session
$ bash hello-all.sh 1 2 3 4
Hello, 1!
Hello, 2!
Hello, 3!
Hello, 4!
```


Let's write a program to print multiplication table. 

```{bash filename=table.sh}
#
# Program to print multiplication table.
#
# USAGE: bash table.sh 5
#

a=$1

for b in 1 2 3 4 5 6 7 8 9 10
do
    echo "$a x $b = $((a * b))"
done
```

We could run the script and pass the number that we want to print the multiplication table.

```session
$ bash table.sh 3
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30

$ bash table.sh 5
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50
```

